blueprint:
  name: Motion-activated Light with Optional Doors
  description: Turn on a light when motion is detected or a door is opened; turn off after motion stops and the wait time elapses.
  domain: automation
  author: Home Assistant (extended)
  source_url: https://github.com/dafal/homeassistant_blueprints/blob/main/motion_light_with_doors.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            device_class: motion
            domain: binary_sensor
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    door_entities:
      name: Door Sensors (optional)
      description: One or more door sensors that will also trigger the light when opened.
      default: []
      selector:
        entity:
          multiple: true
          filter:
            device_class: door
            domain: binary_sensor
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

variables:
  motion_entity: !input motion_entity
  door_entities: !input door_entities

trigger:
  - platform: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input door_entities
    from: "off"
    to: "on"
    enabled: "{{ door_entities | length > 0 }}"

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target: !input light_target
  - alias: "Wait until there is no motion from device"
    wait_template: "{{ is_state(motion_entity, 'off') }}"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - alias: "Turn off the light"
    service: light.turn_off
    target: !input light_target
