blueprint:
  name: "TRV - Sync external temperature (simple)"
  description: "Sync a temperature sensor value to a TRV external temperature number entity."
  domain: automation

  input:
    source_temperature:
      name: Source temperature sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    target_external_temp:
      name: TRV external temperature (number entity)
      selector:
        entity:
          domain: number

mode: single

variables:
  src: !input source_temperature
  dst: !input target_external_temp

trigger:
  - platform: state
    entity_id: !input source_temperature

condition:
  - condition: template
    value_template: >
      {{ states(src) not in ['unknown', 'unavailable', 'none'] }}

action:
  - service: number.set_value
    target:
      entity_id: !input target_external_temp
    data:
      value: "{{ states(src) | float }}"
